### ISSUE TITLE
Error: use of undeclared function native pure function

### ISSUE THREAD

**Issue by andreistefanescu** [asymptotic-code/sui-prover#488]
```
          1 │+[internal] boogie exited with compilation errors:
          2 │+output/tx_context_sender.ok/tx_context_sender::foo_spec_Check.bpl(4689,16): Error: use of undeclared function: $2_tx_context_native_sender$pure
          3 │+output/tx_context_sender.ok/tx_context_sender::foo_spec_Check.bpl(4705,11): Error: use of undeclared function: $2_tx_context_native_sender$pure
          4 │+2 name resolution errors detected in output/tx_context_sender.ok/tx_context_sender::foo_spec_Check.bpl
```
introduced by https://github.com/asymptotic-code/sui/pull/98

**Comment by andreistefanescu** [comment]
@claude no, modify only `model.rs`, that should result in `$pure` not being generated at all
